#!/usr/bin/env python3
"""Stage and serve a Vextro 9 package repository over HTTP.

The Agora app store in the OS fetches an index of key:value blocks and
then downloads each payload with its own HTTP GET.  This script builds
that layout out of the compiled apps and serves it:

    build/repo/index.sr        the index, with real `size:` values
    build/repo/pkg/<id>.vx    the payloads

Usage:
    serve_repo.py [--out DIR] [--port N] [--stage-only] <binary> ...

Each <binary> is a built .vx image whose basename is the package id,
e.g. build/store/mandel.vx.  Packages listed in apps/store/packages.txt
with no matching binary are dropped from the served index.

Inside the guest the repository lives at the QEMU user-networking
gateway, so the default store URL http://10.0.2.2:8000/index.sr reaches
this server with no extra configuration.
"""
import argparse
import http.server
import os
import shutil
import socketserver
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SOURCE_INDEX = os.path.join(ROOT, 'apps', 'store', 'packages.txt')


def parse_blocks(path):
    """Split the source index into [(id, [(key, value), ...]), ...]."""
    blocks = []
    current = None
    with open(path) as fh:
        for raw in fh:
            line = raw.rstrip('\n').rstrip('\r')
            if not line or line.lstrip().startswith('#'):
                continue
            key, _, value = line.partition(':')
            key = key.strip()
            value = value.strip()
            if key == 'pkg':
                current = (value, [])
                blocks.append(current)
            elif current is not None:
                current[1].append((key, value))
    return blocks


def stage(out_dir, binaries):
    pkg_dir = os.path.join(out_dir, 'pkg')
    os.makedirs(pkg_dir, exist_ok=True)

    have = {}
    for path in binaries:
        if not os.path.isfile(path):
            print(f'  skip (not built): {path}', file=sys.stderr)
            continue
        # build/store/mandel.vx -> package id "mandel"
        have[os.path.splitext(os.path.basename(path))[0]] = path

    lines = ['# Vextro 9 package repository',
             '# generated by tools/serve_repo.py', '']
    served = 0

    for pkg_id, fields in parse_blocks(SOURCE_INDEX):
        src = have.get(pkg_id)
        if src is None:
            print(f'  skip (no binary): {pkg_id}', file=sys.stderr)
            continue
        dest = os.path.join(pkg_dir, f'{pkg_id}.vx')
        shutil.copyfile(src, dest)
        size = os.path.getsize(dest)

        lines.append(f'pkg:{pkg_id}')
        for key, value in fields:
            if key == 'size':
                continue
            lines.append(f'{key}:{value}')
        lines.append(f'size:{size}')
        lines.append('')
        served += 1
        print(f'  {pkg_id:<10} {size:>7} bytes')

    index = os.path.join(out_dir, 'index.sr')
    with open(index, 'w') as fh:
        fh.write('\n'.join(lines))

    print(f'staged {served} package(s) in {out_dir}')
    return served


def serve(out_dir, port):
    handler = http.server.SimpleHTTPRequestHandler

    class Handler(handler):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, directory=out_dir, **kwargs)

        def log_message(self, fmt, *args):
            sys.stderr.write('  http: ' + fmt % args + '\n')

    socketserver.TCPServer.allow_reuse_address = True
    with socketserver.TCPServer(('0.0.0.0', port), Handler) as httpd:
        print(f'serving {out_dir} on port {port}')
        print(f'  from the guest:  store repo http://10.0.2.2:{port}/index.sr')
        print('  Ctrl-C to stop')
        try:
            httpd.serve_forever()
        except KeyboardInterrupt:
            print('\nstopped')


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('binaries', nargs='*')
    ap.add_argument('--out', default=os.path.join(ROOT, 'build', 'repo'))
    ap.add_argument('--port', type=int, default=8000)
    ap.add_argument('--stage-only', action='store_true')
    args = ap.parse_args()

    if stage(args.out, args.binaries) == 0:
        print('nothing to serve - run `make` first', file=sys.stderr)
        return 1
    if not args.stage_only:
        serve(args.out, args.port)
    return 0


if __name__ == '__main__':
    sys.exit(main())
